# Generated by Django 3.2.8 on 2021-10-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211026_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='conpass',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
