# Generated by Django 3.2.8 on 2021-10-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='confirmed',
        ),
    ]
